import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_CALIBRATION,serializeCalibration,parseCalibration,calibrationFromHash} from '../src/state';
test('calibration JSON round trips independently',()=>{const c=parseCalibration(serializeCalibration(DEFAULT_CALIBRATION));assert.deepEqual(c,DEFAULT_CALIBRATION);c.eye.z=1;assert.equal(DEFAULT_CALIBRATION.eye.z,350);});
test('URL fragment round trips and empty hash is empty',()=>{const p=new URLSearchParams({calibration:serializeCalibration(DEFAULT_CALIBRATION)});assert.deepEqual(calibrationFromHash('#'+p),DEFAULT_CALIBRATION);assert.equal(calibrationFromHash(''),null);});
test('malformed, unsupported and invalid dimensions rejected',()=>{assert.throws(()=>parseCalibration('{}'));assert.throws(()=>parseCalibration('{'));assert.throws(()=>parseCalibration(JSON.stringify({version:2,calibration:DEFAULT_CALIBRATION})));const c=structuredClone(DEFAULT_CALIBRATION);c.display.widthMm=0;assert.throws(()=>parseCalibration(serializeCalibration(c)));});

test('UI calibration bounds reject extreme small dimensions and coordinates',()=>{for(const widthMm of [1e-308,10001]){const c=structuredClone(DEFAULT_CALIBRATION);c.display.widthMm=widthMm;assert.throws(()=>parseCalibration(serializeCalibration(c)));}const c=structuredClone(DEFAULT_CALIBRATION);c.eye.x=1e308;assert.throws(()=>parseCalibration(serializeCalibration(c)));});

test('inclusive practical limits and malformed numeric values',()=>{for(const widthMm of [.1,10000]){const c=structuredClone(DEFAULT_CALIBRATION);c.display.widthMm=widthMm;assert.equal(parseCalibration(serializeCalibration(c)).display.widthMm,widthMm);}for(const angleDeg of [-3600,3600]){const c=structuredClone(DEFAULT_CALIBRATION);c.display.angleDeg=angleDeg;assert.equal(parseCalibration(serializeCalibration(c)).display.angleDeg,angleDeg);}for(const x of [-1000000,1000000]){const c=structuredClone(DEFAULT_CALIBRATION);c.eye.x=x;assert.equal(parseCalibration(serializeCalibration(c)).eye.x,x);}for(const angleDeg of [-3601,3601,NaN,Infinity]){const c=structuredClone(DEFAULT_CALIBRATION);c.display.angleDeg=angleDeg;assert.throws(()=>parseCalibration(serializeCalibration(c)));}const bad=JSON.parse(serializeCalibration(DEFAULT_CALIBRATION));bad.calibration.eye.x='350';assert.throws(()=>parseCalibration(JSON.stringify(bad)));});
