import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {validateCalibration,projectVirtualPoint,targetUvToWorld,type Calibration} from './geometry';
import {DEFAULT_CALIBRATION,parseCalibration,serializeCalibration,calibrationFromHash,RECORDS_KEY,type Observation} from './state';
import {makeTexture,renderProjection,drawDebug} from './render';
import './style.css';
function download(name:string,content:string,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function initial(){try{return calibrationFromHash(location.hash)||structuredClone(DEFAULT_CALIBRATION)}catch{return structuredClone(DEFAULT_CALIBRATION)}}
function App(){
 const [draft,setDraft]=useState<Calibration>(initial),[active,setActive]=useState<Calibration>(structuredClone(DEFAULT_CALIBRATION));
 const [controlsVisible,setControlsVisible]=useState(true);
 const [fullscreenKind,setFullscreenKind]=useState('Browser viewport');
 const [generated,setGenerated]=useState(false),[message,setMessage]=useState(()=>{try{calibrationFromHash(location.hash);return ''}catch{return 'Invalid calibration URL; default controls loaded.'}}),[experiment,setExperiment]=useState(false),[showRuler,setShowRuler]=useState(false),[mode,setMode]=useState<'projected'|'original'>('projected');
 const [records,setRecords]=useState<Observation[]>(()=>{try{const r=JSON.parse(localStorage.getItem(RECORDS_KEY)||'[]');return Array.isArray(r)?r.filter(v=>v&&typeof v.id==='string'&&typeof v.time==='string'&&v.calibration&&typeof v.success==='string'):[]}catch{return []}});
 const [success,setSuccess]=useState('uncertain'),[clarity,setClarity]=useState(3),[stability,setStability]=useState('not-tested'),[perception,setPerception]=useState('uncertain'),[notes,setNotes]=useState('');
 const [actualAngle,setActualAngle]=useState(30),[actualDistance,setActualDistance]=useState(350);
 const projected=useRef<HTMLCanvasElement>(null),original=useRef<HTMLCanvasElement>(null),debug=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),texture=useRef<HTMLCanvasElement|null>(null);
 const [viewport,setViewport]=useState({width:0,height:0}),[viewportChanged,setViewportChanged]=useState(false);
 const dirty=serializeCalibration(draft)!==serializeCalibration(active);let parameterError='';try{parseCalibration(serializeCalibration(draft))}catch(e){parameterError=(e as Error).message}const valid=validateCalibration(draft);
 useEffect(()=>{texture.current=makeTexture();const ctx=original.current?.getContext('2d');if(ctx)ctx.drawImage(texture.current,0,0,1200,800);},[]);
 useEffect(()=>{if(generated&&projected.current){texture.current=makeTexture(active.target.widthMm/active.target.heightMm);if(original.current){original.current.width=texture.current.width;original.current.height=texture.current.height;original.current.getContext('2d')!.drawImage(texture.current,0,0)}renderProjection(projected.current,active,texture.current);if(debug.current)drawDebug(debug.current,active);}},[active,generated]);
 useEffect(()=>{if(!experiment)return;const measure=()=>{if(stage.current){const r=stage.current.getBoundingClientRect();setViewport(prev=>{if(prev.width&& (Math.abs(prev.width-r.width)>2||Math.abs(prev.height-r.height)>2))setViewportChanged(true);return {width:r.width,height:r.height}})}};measure();window.addEventListener('resize',measure);window.visualViewport?.addEventListener('resize',measure);return()=>{window.removeEventListener('resize',measure);window.visualViewport?.removeEventListener('resize',measure)}} ,[experiment]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setExperiment(false)};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 function change(path:string,value:number){setDraft(old=>{const next=structuredClone(old);const parts=path.split('.');let target=next as unknown as Record<string,unknown>;for(const p of parts.slice(0,-1))target=target[p] as Record<string,unknown>;target[parts.at(-1)!]=value;return next})}
 const field=(label:string,path:string,value:number,unit='mm')=><label className="field" key={path}><span>{label}</span><div><input aria-label={label} type="number" step="any" value={Number.isFinite(value)?value:''} onChange={e=>change(path,e.target.value===''?NaN:Number(e.target.value))}/><span>{unit}</span></div></label>;
 function generate(){if(parameterError){setMessage(parameterError);return}const check=validateCalibration(draft);if(!check.ok){setMessage('Cannot generate: '+check.reason);return}setActive(structuredClone(draft));setGenerated(true);setActualAngle(draft.display.angleDeg);setActualDistance(draft.eye.z);setViewportChanged(false);setViewport({width:0,height:0});setMessage('Static image generated. Parameters are frozen until you generate again.');}
 async function enter(){setMessage('');setControlsVisible(true);setExperiment(true);setShowRuler(false);setViewportChanged(false);setViewport({width:0,height:0});try{if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();setFullscreenKind('Fullscreen')}else{setFullscreenKind('Browser viewport only')}}catch{setFullscreenKind('Browser viewport only');setMessage('Browser fullscreen unavailable. Experiment uses the visible browser viewport; measure that lit area.')}}
 async function exit(){setExperiment(false);if(document.fullscreenElement)await document.exitFullscreen();}
 function saveObservation(){if(!generated)return;if(!Number.isFinite(actualAngle)||Math.abs(actualAngle)>3600||!Number.isFinite(actualDistance)||actualDistance<=0||actualDistance>1000000||!Number.isFinite(clarity)||clarity<1||clarity>5){setMessage('Enter a finite angle (±3600°), positive distance (up to 1,000,000 mm), and clarity from 1 to 5.');return}const record:Observation={id:crypto.randomUUID(),time:new Date().toISOString(),calibration:structuredClone(active),success,clarity,angle:actualAngle,distance:actualDistance,stability,perception,notes,viewport,comparisonMode:mode,raster:{width:projected.current?.width||0,height:projected.current?.height||0},targetId:'HELLO-border-v1'};const next=[record,...records];try{localStorage.setItem(RECORDS_KEY,JSON.stringify(next));setRecords(next);setMessage('Observation saved on this device. No data is sent.')}catch{setMessage('Storage unavailable. Export records before leaving.');setRecords(next)}}
 async function loadFile(file?:File){if(!file)return;if(file.size>1000000){setMessage('Calibration file is too large (maximum 1 MB).');return}try{setDraft(parseCalibration(await file.text()));setMessage('Calibration loaded into controls. Press Generate static image to apply.')}catch(e){setMessage((e as Error).message)}}
 const corners=generated?[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}].map(uv=>projectVirtualPoint(targetUvToWorld(uv,active.target),active)):[];
 const frame=validateCalibration(active);const backface=frame.ok&&((active.eye.x-frame.value.origin.x)*frame.value.normal.x+(active.eye.y-frame.value.origin.y)*frame.value.normal.y+(active.eye.z-frame.value.origin.z)*frame.value.normal.z)<=0;
 const cropped=corners.some(r=>!r.ok||!r.value.insideDisplay);
 return <><div className="shell"><header><a className="wordmark" href="#">A<span>∕</span>DL</a><div className="phase">EXPERIMENT 01 <span>STATIC GEOMETRY</span></div><span className="status"><i/> MANUAL CALIBRATION</span></header>
 <main><section className="intro"><p className="eyebrow">ANAMORPHIC DISPLAY LAB</p><h1>A fixed view.<br/><span>A different plane.</span></h1><p className="lede">One eye. One position. One static image.<br/>Test whether a geometrically corrected target appears independent of a rotated screen.</p><div className="tags"><span>NO TRACKING</span><span>NO ANIMATION</span><span>PHASE 1 ONLY</span></div></section>
 <section className="protocol"><span className="section-no">00</span><div><h2>Calibrate the physical setup first</h2><p>Measure the illuminated area used in experiment mode with a ruler. Enter its real width and height in millimetres. Screen size, CSS pixels and device pixel ratio do not supply physical dimensions.</p><ol><li>Keep the display center at the calibration origin. At 0°, +x points right, +y up and +z toward your eye.</li><li>Place one eye at the entered x/y/z position. Close the other eye. Measure distance along +z from the unrotated display plane.</li><li>Rotate the screen around the entered world-space Y-axis pivot. Positive angle: right edge moves away, left edge toward you. Keep your eye and virtual plane fixed.</li><li>Generate once, enter experiment mode, and compare the original with the projected target. Record what you actually see.</li></ol><p className="fine">iPhone / iOS Safari may not support true fullscreen. Browser bars reduce the lit viewport. Measure the actual black rectangle, keep browser chrome stable, and recalibrate after any viewport change. Add to Home Screen if useful; it still requires measurement.</p></div></section>
 <div className="workspace"><section className="controls panel"><div className="section-heading"><span className="section-no">01</span><h2>Physical parameters</h2></div><p className="muted">World coordinates in mm · right-handed +Y rotation</p>
 <fieldset><legend>Illuminated display area</legend><div className="fields">{field('Width','display.widthMm',draft.display.widthMm)}{field('Height','display.heightMm',draft.display.heightMm)}{field('Y rotation','display.angleDeg',draft.display.angleDeg,'deg')}</div></fieldset>
 <fieldset><legend>Fixed eye position</legend><div className="fields">{field('Eye x','eye.x',draft.eye.x)}{field('Eye y','eye.y',draft.eye.y)}{field('Eye distance z','eye.z',draft.eye.z)}</div></fieldset>
 <fieldset><legend>Rotation pivot · world space</legend><div className="fields">{field('Pivot x','display.pivot.x',draft.display.pivot.x)}{field('Pivot y','display.pivot.y',draft.display.pivot.y)}{field('Pivot z','display.pivot.z',draft.display.pivot.z)}</div><p className="fine">Pivot y does not change rotation about the Y axis</p></fieldset>
 <fieldset><legend>World-fixed virtual plane · parallel to XY</legend><div className="fields">{field('Plane width','target.widthMm',draft.target.widthMm)}{field('Plane height','target.heightMm',draft.target.heightMm)}{field('Plane x','target.center.x',draft.target.center.x)}{field('Plane y','target.center.y',draft.target.center.y)}{field('Plane z','target.center.z',draft.target.center.z)}</div></fieldset>
 {parameterError&&<p className="warning" role="alert">{parameterError}</p>}
 {!valid.ok&&<p className="warning" role="alert">Invalid geometry: {valid.reason}. Change the setup before generating.</p>}
 <button className="primary" disabled={!valid.ok||!!parameterError} onClick={generate}>Generate static image <span>↗</span></button><p className="fine">{dirty&&generated?'Unapplied changes. The displayed image still uses the last generated setup.':'Changes never update the image automatically.'}</p>
 <details><summary>Save & restore calibration</summary><div className="button-row"><button onClick={()=>{if(!valid.ok||parameterError)return;const h=new URLSearchParams({calibration:serializeCalibration(draft)});history.replaceState(null,'','#'+h);navigator.clipboard?.writeText(location.href).then(()=>setMessage('Calibration URL copied. It contains parameters only.')).catch(()=>setMessage('Calibration is in the address bar. Copy that URL to share.'));setMessage('Calibration saved in the address bar.')}}>Save URL</button><button onClick={()=>{if(valid.ok&&!parameterError)download('anamorphic-calibration.json',serializeCalibration(draft))}}>Export JSON</button><label className="file-button">Import JSON<input type="file" accept="application/json,.json" onChange={e=>{void loadFile(e.target.files?.[0]);e.target.value=''}}/></label><button onClick={()=>setDraft(structuredClone(DEFAULT_CALIBRATION))}>Reset controls</button></div></details></section>
 <section className="preview panel"><div className="section-heading"><span className="section-no">02</span><h2>Static projection</h2><span className="chip">{generated?'GENERATED':'AWAITING GENERATION'}</span></div><p className="muted">Preview is scaled. Only the calibrated experiment viewport has physical meaning.</p>
 <div className="preview-grid"><figure><div className="original-wrap" style={{aspectRatio:`${active.target.widthMm} / ${active.target.heightMm}`}}><canvas ref={original} width="1200" height="800"/></div><figcaption><span>01 / Original target</span><span>HELLO + border</span></figcaption></figure><figure><div className="projected-wrap" style={{aspectRatio:`${active.display.widthMm} / ${active.display.heightMm}`}}>{!generated&&<div className="empty">Ready when<br/>you are <span>Set dimensions, then generate ↗</span></div>}<canvas ref={projected} style={{visibility:generated?'visible':'hidden'}}/></div><figcaption><span>02 / Projected display</span><span>{generated?`${active.display.angleDeg}° Y rotation`:'Not generated'}</span></figcaption></figure></div>
 {corners.length>0&&corners.every(r=>!r.ok)&&<p className="warning">No target corners can be projected. The target may be behind the eye or the rays may be parallel. The black output is not evidence of success.</p>}
 {generated&&backface&&<p className="warning">Eye is behind the display front face; the physical screen may not be visible.</p>}
 {cropped&&<p className="warning">Some target corners are outside the display or cannot be projected. Clipping is physical; no correction or automatic fit is applied.</p>}
 <div className="button-row"><button className="primary" disabled={!generated} onClick={()=>void enter()}>Open experiment ↗</button><button disabled={!generated} onClick={()=>{const canvas=projected.current;if(!canvas)return;const a=document.createElement('a');a.download='anamorphic-static.png';a.href=canvas.toDataURL('image/png');a.click();}}>Export PNG ↓</button></div><p className="fine">PNG maps edge-to-edge to the entered physical display area. Resolution is bounded to 1800 px on the longest side; extreme aspect ratios lose detail. Do not display it at an arbitrary size.</p>
 </section></div>
 <section className="debug panel"><div className="section-heading"><span className="section-no">03</span><h2>Geometry, in plain sight</h2></div><p className="muted">Green: world-fixed virtual plane · Blue: rotated physical display · White point: fixed eye · Lines: corner rays</p>{generated?<canvas ref={debug}/>:<div className="debug-empty">Generate a static image to inspect its ray geometry</div>}<p className="fine">The target and display coincide at zero rotation and zero plane offset. At 30°, the plane remains at the calibration origin while the physical display rotates. This diagram is explanatory, not a perceptual simulation.</p></section>
 <section className="observations panel"><div className="section-heading"><span className="section-no">04</span><h2>Record the observation</h2><span className="chip">LOCAL ONLY</span></div><p className="muted">Geometric correctness does not prove a floating or independent-plane percept. Record failure and uncertainty too.</p><div className="observation-fields"><label>Perceptual success<select value={success} onChange={e=>setSuccess(e.target.value)}><option value="uncertain">Uncertain</option><option value="yes">Yes</option><option value="no">No</option></select></label><label>Clarity · 1 low → 5 high<input type="number" min="1" max="5" value={clarity} onChange={e=>setClarity(Math.max(1,Math.min(5,Number(e.target.value))))}/></label><label>Observed angle · deg<input type="number" value={actualAngle} onChange={e=>setActualAngle(Number(e.target.value))}/></label><label>Eye distance · mm<input type="number" value={actualDistance} onChange={e=>setActualDistance(Number(e.target.value))}/></label><label>Stability<select value={stability} onChange={e=>setStability(e.target.value)}><option value="not-tested">Not tested</option><option>Stable at fixed eye</option><option>Fragile / intermittent</option><option>Unstable</option></select></label><label>Appeared as<select value={perception} onChange={e=>setPerception(e.target.value)}><option value="uncertain">Uncertain</option><option>Attached to screen</option><option>Independent plane</option><option>No clear target</option></select></label></div><label className="notes">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Eye placement, ruler measurement, browser viewport, what worked or failed…"/></label><div className="button-row"><button disabled={!generated} onClick={saveObservation}>Save observation</button><button disabled={!records.length} onClick={()=>download('anamorphic-observations.json',JSON.stringify({version:1,observations:records},null,2))}>Export {records.length} records ↓</button></div><div className="record-list">{records.slice(0,5).map(r=><div className="record" key={r.id}><div><strong>{new Date(r.time).toLocaleString()}</strong><span>{r.success} · clarity {r.clarity}/5 · {r.angle}° · {r.distance} mm · {r.perception}</span></div><button onClick={()=>{setDraft(structuredClone(r.calibration));setMessage('Observation calibration loaded into controls. Generate to apply.')}}>Load calibration</button></div>)}</div><p className="fine">Records use the last generated calibration and the last comparison mode. A 0 × 0 viewport means experiment mode was not opened for this image. Browser storage can be cleared; export to keep a copy.</p></section>
 <footer><span>ANAMORPHIC DISPLAY LAB / PHASE 1</span><p>Static projection only. Sensors, camera, tracking and animation remain out of scope until this test is evaluated.</p></footer></main></div>
 {message&&<div className="toast" role="status">{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></div>}
 {experiment&&<div className="experiment" ref={stage} onClick={()=>{if(!controlsVisible)setControlsVisible(true)}}><img className="experiment-image" alt={mode==='projected'?'Generated static anamorphic target':'Original unwarped target'} src={mode==='projected'?projected.current?.toDataURL():texture.current?.toDataURL()} style={mode==='projected'?{}:{width:`${active.target.widthMm/active.display.widthMm*100}%`,height:`${active.target.heightMm/active.display.heightMm*100}%`,left:`${50+active.target.center.x/active.display.widthMm*100}%`,top:`${50-active.target.center.y/active.display.heightMm*100}%`,transform:'translate(-50%,-50%)'}}/>{showRuler&&<div className="ruler" style={{width:`${20/active.display.widthMm*100}%`}}>20 mm</div>}{controlsVisible&&<div className="experiment-toolbar"><button onClick={()=>setMode(mode==='projected'?'original':'projected')}>{mode==='projected'?'Projected':'Original'} · switch</button><button onClick={()=>setShowRuler(!showRuler)}>20 mm ruler</button><button onClick={()=>{setControlsVisible(false);setShowRuler(false)}}>Hide controls · tap to restore</button><button onClick={()=>void exit()}>Exit ×</button><p>{fullscreenKind} · {Math.round(viewport.width)} × {Math.round(viewport.height)} CSS px → {active.display.widthMm} × {active.display.heightMm} mm {viewportChanged?' · VIEWPORT CHANGED: exit and remeasure':''}{viewport.width>0&&Math.abs(viewport.width/viewport.height-active.display.widthMm/active.display.heightMm)>.04?' · ASPECT MISMATCH: measure this viewport':''}</p></div>}</div>}
 </>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
