import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {validateCalibration,projectVirtualPoint,targetUvToWorld,type Calibration} from './geometry';
import {DEFAULT_CALIBRATION,serializeCalibration,calibrationFromHash,settingsFromHash,parseSettings,RECORDS_KEY,type Observation} from './state';
import {makeTexture,renderComparison,drawDebug} from './render';
import {geometryErrorLabel,localizeError,observationLabel} from './localization';
import {estimateDeviceCalibration,estimateViewportMm,calibrationFromDevicePreset,DEVICE_CALIBRATION_PRESETS,type DeviceCalibrationProfile} from './device-calibration';
import {DEFAULT_GRIDS,parseGrids,type GridSettings} from './grids';
import './style.css';
function download(name:string,content:string,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function deviceInput(){return {userAgent:navigator.userAgent,screenWidth:screen.width,screenHeight:screen.height,devicePixelRatio:window.devicePixelRatio||1};}
function readUrlCalibration(){try{return calibrationFromHash(location.hash)}catch{return null}}
function initialGrids(){try{return settingsFromHash(location.hash)?.grids||{...DEFAULT_GRIDS}}catch{return {...DEFAULT_GRIDS}}}
function panelDimensions(profile:DeviceCalibrationProfile){return screen.width>screen.height?{widthMm:profile.fullHeightMm,heightMm:profile.fullWidthMm}:{widthMm:profile.fullWidthMm,heightMm:profile.fullHeightMm};}
function initial(){const saved=readUrlCalibration();if(saved)return saved;const c=structuredClone(DEFAULT_CALIBRATION),profile=estimateDeviceCalibration(deviceInput());if(profile.identified)Object.assign(c.display,panelDimensions(profile));return c;}
function App(){
 const [draft,setDraft]=useState<Calibration>(initial),[active,setActive]=useState<Calibration>(structuredClone(DEFAULT_CALIBRATION));
 const [draftGrids,setDraftGrids]=useState<GridSettings>(initialGrids),[activeGrids,setActiveGrids]=useState<GridSettings>({...DEFAULT_GRIDS});
 const [deviceProfile,setDeviceProfile]=useState(()=>estimateDeviceCalibration(deviceInput()));
 const [deviceChoice,setDeviceChoice]=useState(()=>readUrlCalibration()?'manual':'auto');
 const [autoDimensions,setAutoDimensions]=useState(()=>!readUrlCalibration()&&estimateDeviceCalibration(deviceInput()).identified);
 const [imageUrls,setImageUrls]=useState({projected:'',original:''});
 const [controlsVisible,setControlsVisible]=useState(true);
 const [fullscreenKind,setFullscreenKind]=useState('브라우저 표시 영역');
 const [generated,setGenerated]=useState(false),[message,setMessage]=useState(()=>{try{calibrationFromHash(location.hash);return ''}catch{return '보정 URL이 올바르지 않아 기본 설정을 불러왔습니다.'}}),[experiment,setExperiment]=useState(false),[showRuler,setShowRuler]=useState(false),[mode,setMode]=useState<'projected'|'original'>('projected');
 const [records,setRecords]=useState<Observation[]>(()=>{try{const r=JSON.parse(localStorage.getItem(RECORDS_KEY)||'[]');return Array.isArray(r)?r.filter(v=>v&&typeof v.id==='string'&&typeof v.time==='string'&&v.calibration&&typeof v.success==='string'):[]}catch{return []}});
 const [success,setSuccess]=useState('uncertain'),[clarity,setClarity]=useState(3),[stability,setStability]=useState('not-tested'),[perception,setPerception]=useState('uncertain'),[notes,setNotes]=useState('');
 const [actualAngle,setActualAngle]=useState(30),[actualDistance,setActualDistance]=useState(350);
 const projected=useRef<HTMLCanvasElement>(null),original=useRef<HTMLCanvasElement>(null),debug=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),texture=useRef<HTMLCanvasElement|null>(null);
 const [viewport,setViewport]=useState({width:0,height:0}),[viewportChanged,setViewportChanged]=useState(false),[zoomChanged,setZoomChanged]=useState(false);
 const dirty=serializeCalibration(draft,draftGrids)!==serializeCalibration(active,activeGrids);let parameterError='';try{parseSettings(serializeCalibration(draft,draftGrids))}catch(e){parameterError=localizeError(e)}const valid=validateCalibration(draft);
 useEffect(()=>{texture.current=makeTexture();const ctx=original.current?.getContext('2d');if(ctx)ctx.drawImage(texture.current,0,0,1200,800);},[]);
 useEffect(()=>{if(generated&&projected.current){
  texture.current=makeTexture(active.target.widthMm/active.target.heightMm,activeGrids.plane?{...active.target,spacingMm:activeGrids.planeSpacingMm}:undefined);
  if(original.current){original.current.width=texture.current.width;original.current.height=texture.current.height;original.current.getContext('2d')!.drawImage(texture.current,0,0)}
  renderComparison(projected.current,active,texture.current,activeGrids);
  const baseline=document.createElement('canvas');renderComparison(baseline,active,texture.current,activeGrids,'original');
  if(debug.current)drawDebug(debug.current,active);
  setImageUrls({projected:projected.current.toDataURL(),original:baseline.toDataURL()});
 }},[active,activeGrids,generated]);
 useEffect(()=>{if(!experiment)return;const measure=()=>{setZoomChanged(Math.abs((window.visualViewport?.scale||1)-1)>.01);if(stage.current){const r=stage.current.getBoundingClientRect();setViewport(prev=>{if(prev.width&& (Math.abs(prev.width-r.width)>2||Math.abs(prev.height-r.height)>2))setViewportChanged(true);return {width:r.width,height:r.height}})}};measure();window.addEventListener('resize',measure);window.visualViewport?.addEventListener('resize',measure);return()=>{window.removeEventListener('resize',measure);window.visualViewport?.removeEventListener('resize',measure)}} ,[experiment]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setExperiment(false)};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 function change(path:string,value:number){if(path==='display.widthMm'||path==='display.heightMm'){setAutoDimensions(false);setDeviceChoice('manual')}setDraft(old=>{const next=structuredClone(old);const parts=path.split('.');let target=next as unknown as Record<string,unknown>;for(const p of parts.slice(0,-1))target=target[p] as Record<string,unknown>;target[parts.at(-1)!]=value;return next})}
 const field=(label:string,path:string,value:number,unit='mm')=><label className="field" key={path}><span>{label}</span><div><input aria-label={label} type="number" step="any" value={Number.isFinite(value)?value:''} onChange={e=>change(path,e.target.value===''?NaN:Number(e.target.value))}/><span>{unit}</span></div></label>;
 function generate(){if(parameterError){setMessage(parameterError);return}const check=validateCalibration(draft);if(!check.ok){setMessage('이미지를 생성할 수 없습니다: '+geometryErrorLabel(check.reason));return}setActive(structuredClone(draft));setActiveGrids(structuredClone(draftGrids));setGenerated(true);setActualAngle(draft.display.angleDeg);setActualDistance(draft.eye.z);setViewportChanged(false);setViewport({width:0,height:0});setMessage('정적 이미지를 생성했습니다. 기기 규격 자동 적용 모드에서는 실험 화면 진입 시 표시 영역 크기를 한 번 보정합니다.');}
 function selectDevice(choice:string){
  setDeviceChoice(choice);
  if(choice==='manual'){setAutoDimensions(false);return;}
  const profile=choice==='auto'?estimateDeviceCalibration(deviceInput()):calibrationFromDevicePreset(choice,deviceInput());
  if(!profile)return;
  setDeviceProfile(profile);setAutoDimensions(profile.identified);
  if(profile.identified)setDraft(old=>({...old,display:{...old.display,...panelDimensions(profile)}}));
  setMessage(profile.identified?'화면 사양의 추정 크기를 적용했습니다. 실험 모드를 열 때 실제 표시 영역에 맞춰 한 번 보정합니다.':'이 기기의 화면 크기를 자동으로 확인할 수 없습니다. 기기 규격을 선택하거나 실제 치수를 입력하세요.');
 }
 function applyViewportEstimate(){
  if(!autoDimensions||!deviceProfile.identified||!stage.current)return;
  const scale=window.visualViewport?.scale||1;
  if(Math.abs(scale-1)>.01){setMessage('브라우저 확대를 100%로 되돌린 뒤 표시 영역 크기를 다시 적용하세요.');return;}
  const r=stage.current.getBoundingClientRect();
  const orientation=screen.orientation?.type?.startsWith('landscape')?'landscape':screen.orientation?.type?.startsWith('portrait')?'portrait':screen.width>screen.height?'landscape':'portrait';
  const size=estimateViewportMm(deviceProfile,r.width,r.height,orientation,scale);
  const next=structuredClone(active);next.display.widthMm=Math.round(size.widthMm*100)/100;next.display.heightMm=Math.round(size.heightMm*100)/100;
  if(!validateCalibration(next).ok)return;
  setActive(next);setDraft(old=>({...old,display:{...old.display,widthMm:next.display.widthMm,heightMm:next.display.heightMm}}));
  setViewport({width:r.width,height:r.height});setViewportChanged(false);
 }
 async function enter(){
  setMessage('');setControlsVisible(true);setExperiment(true);setShowRuler(false);setViewportChanged(false);setViewport({width:0,height:0});
  try{if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();setFullscreenKind('전체 화면')}else{setFullscreenKind('브라우저 표시 영역만 사용')}}catch{setFullscreenKind('브라우저 표시 영역만 사용');setMessage('이 브라우저에서는 전체 화면을 사용할 수 없습니다. 현재 브라우저에 보이는 실험 영역을 사용합니다.');}
  // Apply once after fullscreen layout settles; later viewport changes only warn.
  await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));
  applyViewportEstimate();
 }

 async function exit(){setExperiment(false);if(document.fullscreenElement)await document.exitFullscreen();}
 function saveObservation(){if(!generated)return;if(!Number.isFinite(actualAngle)||Math.abs(actualAngle)>3600||!Number.isFinite(actualDistance)||actualDistance<=0||actualDistance>1000000||!Number.isFinite(clarity)||clarity<1||clarity>5){setMessage('각도는 ±3600° 이내, 거리는 0보다 크고 1,000,000 mm 이하, 선명도는 1~5의 숫자로 입력하세요.');return}const record:Observation={id:crypto.randomUUID(),time:new Date().toISOString(),calibration:structuredClone(active),success,clarity,angle:actualAngle,distance:actualDistance,stability,perception,notes,viewport,comparisonMode:mode,raster:{width:projected.current?.width||0,height:projected.current?.height||0},targetId:'HELLO-border-v1',grids:structuredClone(activeGrids)};const next=[record,...records];try{localStorage.setItem(RECORDS_KEY,JSON.stringify(next));setRecords(next);setMessage('관찰 기록을 이 기기에 저장했습니다. 데이터는 외부로 전송되지 않습니다.')}catch{setMessage('브라우저 저장 공간을 사용할 수 없습니다. 페이지를 떠나기 전에 기록을 내보내세요.');setRecords(next)}}
 async function loadFile(file?:File){if(!file)return;if(file.size>1000000){setMessage('보정 파일이 너무 큽니다. 최대 1 MB까지 불러올 수 있습니다.');return}try{const saved=parseSettings(await file.text());setDraft(saved.calibration);setDraftGrids(saved.grids);setAutoDimensions(false);setDeviceChoice('manual');setMessage('보정값을 입력란에 불러왔습니다. 정적 이미지 생성을 눌러 적용하세요.')}catch(e){setMessage(localizeError(e))}}
 const corners=generated?[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}].map(uv=>projectVirtualPoint(targetUvToWorld(uv,active.target),active)):[];
 const frame=validateCalibration(active);const backface=frame.ok&&((active.eye.x-frame.value.origin.x)*frame.value.normal.x+(active.eye.y-frame.value.origin.y)*frame.value.normal.y+(active.eye.z-frame.value.origin.z)*frame.value.normal.z)<=0;
 const cropped=corners.some(r=>!r.ok||!r.value.insideDisplay);
 return <><div className="shell"><header><a className="wordmark" href="#">A<span>∕</span>DL</a><div className="phase">실험 01 <span>정적 투영 기하</span></div><span className="status"><i/> 수동 보정</span></header>
 <main><section className="intro"><p className="eyebrow">아나모픽 디스플레이 실험실</p><h1>고정된 시점.<br/><span>다르게 보이는 평면.</span></h1><p className="lede">한쪽 눈. 하나의 위치. 한 장의 정적 이미지.<br/>기하학적으로 보정한 표적이 회전된 화면과 별개의 평면으로 보이는지 실험합니다.</p><div className="tags"><span>시점 추적 없음</span><span>애니메이션 없음</span><span>1단계 실험</span></div></section>
 <section className="protocol"><span className="section-no">00</span><div><h2>먼저 실제 실험 환경을 보정하세요</h2><p>실험 모드에서 사용하는 표시 영역을 자로 재고, 실제 가로·세로 길이를 mm 단위로 입력하세요. 알려진 기기는 제조사 화면 사양으로 시작값을 추정할 수 있지만, 브라우저 정보만으로 기종이나 실제 크기를 확정할 수는 없습니다. 정확한 실험에는 자로 확인한 치수를 사용하세요.</p><ol><li>화면 중심을 보정 좌표계의 원점에 맞추세요. 회전각 0°에서 +x는 오른쪽, +y는 위쪽, +z는 눈을 향합니다.</li><li>한쪽 눈을 입력한 x/y/z 위치에 두고 다른 눈은 감으세요. 거리는 회전 전 화면 평면에서 +z 방향으로 측정합니다.</li><li>입력한 공간 좌표의 회전 중심을 지나는 Y축을 기준으로 화면을 돌리세요. 양의 각도에서는 오른쪽 가장자리가 멀어지고 왼쪽 가장자리가 가까워집니다. 눈과 가상 평면의 위치는 고정하세요.</li><li>이미지를 한 번 생성한 뒤 실험 모드에서 원본과 보정된 표적을 비교하고, 실제로 보이는 결과를 기록하세요.</li></ol><p className="fine">iPhone의 iOS Safari에서는 전체 화면이 지원되지 않을 수 있습니다. 주소창과 도구 모음이 표시 영역을 줄이므로 실제 검은 직사각형 영역을 측정하세요. 브라우저 표시줄 상태를 유지하고, 표시 영역이 바뀌면 다시 보정하세요. 홈 화면에 추가해 사용할 때도 실제 크기를 확인해야 합니다.</p></div></section>
 <div className="workspace"><section className="controls panel"><div className="section-heading"><span className="section-no">01</span><h2>실제 치수와 위치</h2></div><p className="muted">공간 좌표 단위: mm · 오른손 법칙에 따른 +Y축 회전</p>
 <fieldset><legend>기기 화면 규격</legend><label className="field"><span>크기 설정 방식</span><select aria-label="크기 설정 방식" value={deviceChoice} onChange={e=>selectDevice(e.target.value)}><option value="auto">기기 정보로 자동 추정</option>{DEVICE_CALIBRATION_PRESETS.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}<option value="manual">직접 입력 / 불러온 보정값</option></select></label><p className="fine">{deviceChoice==='manual'?'직접 입력하거나 불러온 치수를 유지합니다. 다시 추정하려면 위에서 자동 추정 또는 기기 규격을 선택하세요.':deviceProfile.label}</p>{deviceChoice!=='manual'&&<><p className="fine">{deviceProfile.warnings.join(' ')}</p><p className="fine">{autoDimensions?'실험 모드를 열 때 현재 표시 영역의 비율로 크기를 한 번 계산합니다. 이후 화면이 바뀌면 다시 적용하세요.':'자동 적용이 꺼져 있습니다. 기기 규격을 선택하거나 자로 잰 치수를 입력하세요.'}</p>{deviceProfile.sources.length>0&&<details><summary>화면 사양 근거</summary>{deviceProfile.sources.map((url,i)=><p key={url}><a href={url} target="_blank" rel="noreferrer">제조사 화면 사양 {i+1}</a></p>)}</details>}</>}</fieldset>
 <fieldset><legend>실험 표시 영역</legend><div className="fields">{field('가로 길이','display.widthMm',draft.display.widthMm)}{field('세로 길이','display.heightMm',draft.display.heightMm)}{field('Y축 회전각','display.angleDeg',draft.display.angleDeg,'°')}</div></fieldset>
 <fieldset><legend>고정된 눈 위치</legend><div className="fields">{field('눈 x','eye.x',draft.eye.x)}{field('눈 y','eye.y',draft.eye.y)}{field('눈 거리 z','eye.z',draft.eye.z)}</div></fieldset>
 <fieldset><legend>회전 중심 · 공간 좌표</legend><div className="fields">{field('회전 중심 x','display.pivot.x',draft.display.pivot.x)}{field('회전 중심 y','display.pivot.y',draft.display.pivot.y)}{field('회전 중심 z','display.pivot.z',draft.display.pivot.z)}</div><p className="fine">회전 중심의 y값은 Y축 회전에 영향을 주지 않습니다</p></fieldset>
 <fieldset><legend>공간에 고정된 가상 평면 · XY 평면과 평행</legend><div className="fields">{field('평면 가로','target.widthMm',draft.target.widthMm)}{field('평면 세로','target.heightMm',draft.target.heightMm)}{field('평면 x','target.center.x',draft.target.center.x)}{field('평면 y','target.center.y',draft.target.center.y)}{field('평면 z','target.center.z',draft.target.center.z)}</div></fieldset>
 <fieldset className="grid-settings"><legend>비교 격자 · 각각 표시 / 숨기기</legend>
 <label className="grid-toggle screen-grid"><input type="checkbox" checked={draftGrids.screen} onChange={e=>setDraftGrids(g=>({...g,screen:e.target.checked}))}/>화면 격자 · 하늘색 점선</label>
 <label className="field"><span>화면 격자 간격</span><div><input aria-label="화면 격자 간격" type="number" min="1" max="1000" step="1" value={Number.isFinite(draftGrids.screenSpacingMm)?draftGrids.screenSpacingMm:''} onChange={e=>setDraftGrids(g=>({...g,screenSpacingMm:e.target.value===''?NaN:Number(e.target.value)}))}/><span>mm</span></div></label>
 <label className="grid-toggle plane-grid"><input type="checkbox" checked={draftGrids.plane} onChange={e=>setDraftGrids(g=>({...g,plane:e.target.checked}))}/>평면 격자 · 연두색 실선</label>
 <label className="field"><span>평면 격자 간격</span><div><input aria-label="평면 격자 간격" type="number" min="1" max="1000" step="1" value={Number.isFinite(draftGrids.planeSpacingMm)?draftGrids.planeSpacingMm:''} onChange={e=>setDraftGrids(g=>({...g,planeSpacingMm:e.target.value===''?NaN:Number(e.target.value)}))}/><span>mm</span></div></label>
 <p className="fine">화면 격자는 표시 영역의 중심에 고정되고, 평면 격자는 가상 평면의 중심을 기준으로 글자·테두리와 함께 투영됩니다. 두 격자를 동시에 비교할 수 있습니다. 간격은 각 평면의 mm 단위이며, 화면에서 잰 크기는 보정 정확도에 따라 달라집니다. 이미지 생성 버튼으로 적용하세요.</p></fieldset>
 {parameterError&&<p className="warning" role="alert">{parameterError}</p>}
 {!valid.ok&&<p className="warning" role="alert">기하 설정 오류: {geometryErrorLabel(valid.reason)}. 설정을 수정한 뒤 이미지를 생성하세요.</p>}
 <button className="primary" disabled={!valid.ok||!!parameterError} onClick={generate}>정적 이미지 생성 <span>↗</span></button><p className="fine">{dirty&&generated?'아직 적용하지 않은 변경사항이 있습니다. 현재 이미지는 마지막으로 생성한 설정을 사용합니다.':'입력값 변경은 이미지 생성 버튼으로 적용합니다. 기기 규격 모드에서는 실험 진입 또는 크기 다시 적용 시 표시 영역 크기를 보정합니다.'}</p>
 <details><summary>보정값 저장 및 불러오기</summary><div className="button-row"><button onClick={()=>{if(!valid.ok||parameterError)return;const h=new URLSearchParams({calibration:serializeCalibration(draft,draftGrids)});history.replaceState(null,'','#'+h);navigator.clipboard?.writeText(location.href).then(()=>setMessage('보정 URL을 복사했습니다. URL에는 설정값만 포함됩니다.')).catch(()=>setMessage('주소창에 보정값을 저장했습니다. 공유하려면 주소를 복사하세요.'));setMessage('주소창에 보정값을 저장했습니다.')}}>보정 URL 저장</button><button onClick={()=>{if(valid.ok&&!parameterError)download('anamorphic-calibration.json',serializeCalibration(draft,draftGrids))}}>JSON 내보내기</button><label className="file-button">JSON 불러오기<input type="file" accept="application/json,.json" onChange={e=>{void loadFile(e.target.files?.[0]);e.target.value=''}}/></label><button onClick={()=>{setDraft(structuredClone(DEFAULT_CALIBRATION));setDraftGrids({...DEFAULT_GRIDS});setAutoDimensions(false);setDeviceChoice('manual')}}>입력값 초기화</button></div></details></section>
 <section className="preview panel"><div className="section-heading"><span className="section-no">02</span><h2>정적 투영 이미지</h2><span className="chip">{generated?'생성 완료':'생성 대기'}</span></div><p className="muted">미리보기는 축소된 이미지입니다. 실제 치수는 보정된 실험 표시 영역에서만 유효합니다.</p>
 <div className="preview-grid"><figure><div className="original-wrap" style={{aspectRatio:`${active.target.widthMm} / ${active.target.heightMm}`}}><canvas ref={original} width="1200" height="800"/></div><figcaption><span>01 / 원본 표적</span><span>HELLO + 테두리{activeGrids.plane&&generated?' + 평면 격자':''}</span></figcaption></figure><figure><div className="projected-wrap" style={{aspectRatio:`${active.display.widthMm} / ${active.display.heightMm}`}}>{!generated&&<div className="empty">크기를 입력하고<br/>시작하세요 <span>실제 치수 설정 후 이미지 생성 ↗</span></div>}<canvas ref={projected} style={{visibility:generated?'visible':'hidden'}}/></div><figcaption><span>02 / 보정된 화면</span><span>{generated?`${active.display.angleDeg}° Y축 회전`:'생성 전'}</span></figcaption></figure></div>
 {corners.length>0&&corners.every(r=>!r.ok)&&<p className="warning">표적의 꼭짓점을 하나도 투영할 수 없습니다. 표적이 눈 뒤에 있거나 광선이 화면과 평행할 수 있습니다. 검은 출력 화면은 실험 성공을 뜻하지 않습니다.</p>}
 {generated&&backface&&<p className="warning">눈이 화면 앞면의 뒤쪽에 있습니다. 실제 화면이 보이지 않을 수 있습니다.</p>}
 {cropped&&<p className="warning">일부 꼭짓점이 화면 밖에 있거나 투영할 수 없습니다. 실제 화면 경계에서 잘리는 현상이며, 자동 맞춤이나 추가 보정은 적용하지 않습니다.</p>}
 <div className="button-row"><button className="primary" disabled={!generated} onClick={()=>void enter()}>실험 모드 열기 ↗</button><button disabled={!generated} onClick={()=>{const url=imageUrls[mode];if(!url)return;const a=document.createElement('a');a.download=`anamorphic-${mode}.png`;a.href=url;a.click();}}>PNG 내보내기 ↓</button></div><p className="fine">PNG에는 마지막 비교 모드의 이미지와 적용된 두 격자가 포함됩니다. PNG는 입력한 실제 표시 영역의 가장자리에 맞춰 표시해야 합니다. 긴 변의 해상도는 최대 1800 px이며, 가로세로 비율이 극단적이면 세부 표현이 줄어듭니다. 임의의 크기로 표시하지 마세요.</p>
 </section></div>
 <section className="debug panel"><div className="section-heading"><span className="section-no">03</span><h2>투영 기하 한눈에 보기</h2></div><p className="muted">초록색: 공간에 고정된 가상 평면 · 파란색: 회전된 실제 화면 · 흰 점: 고정된 눈 · 선: 꼭짓점을 잇는 광선</p>{generated?<canvas ref={debug}/>:<div className="debug-empty">정적 이미지를 생성하면 광선의 기하 구조를 볼 수 있습니다</div>}<p className="fine">회전각과 가상 평면의 위치 오프셋이 모두 0이면 두 평면이 겹칩니다. 회전각 30°에서는 실제 화면이 회전해도 가상 평면은 보정 원점에 남아 있습니다. 이 도식은 기하 설명용이며, 눈에 보이는 장면을 시뮬레이션한 것은 아닙니다.</p></section>
 <section className="observations panel"><div className="section-heading"><span className="section-no">04</span><h2>관찰 결과 기록</h2><span className="chip">이 기기에만 저장</span></div><p className="muted">기하학적으로 올바르다고 해서 표적이 떠 있거나 독립된 평면으로 보이는 것은 아닙니다. 실패하거나 확신이 없는 결과도 기록하세요.</p><div className="observation-fields"><label>별개의 평면으로 보였나요?<select value={success} onChange={e=>setSuccess(e.target.value)}><option value="uncertain">확실하지 않음</option><option value="yes">예</option><option value="no">아니요</option></select></label><label>선명도 · 1 낮음 → 5 높음<input type="number" min="1" max="5" value={clarity} onChange={e=>setClarity(Math.max(1,Math.min(5,Number(e.target.value))))}/></label><label>실제 관찰 각도 · °<input type="number" value={actualAngle} onChange={e=>setActualAngle(Number(e.target.value))}/></label><label>눈과의 거리 · mm<input type="number" value={actualDistance} onChange={e=>setActualDistance(Number(e.target.value))}/></label><label>안정성<select value={stability} onChange={e=>setStability(e.target.value)}><option value="not-tested">미확인</option><option value="Stable at fixed eye">눈 위치를 고정하면 안정적</option><option value="Fragile / intermittent">쉽게 깨짐 / 간헐적</option><option value="Unstable">불안정</option></select></label><label>보인 형태<select value={perception} onChange={e=>setPerception(e.target.value)}><option value="uncertain">확실하지 않음</option><option value="Attached to screen">화면에 붙어 보임</option><option value="Independent plane">독립된 평면으로 보임</option><option value="No clear target">표적이 뚜렷하지 않음</option></select></label></div><label className="notes">관찰 메모<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="눈 위치, 자로 잰 크기, 브라우저 표시 영역, 성공하거나 실패한 점 등을 적어주세요…"/></label><div className="button-row"><button disabled={!generated} onClick={saveObservation}>관찰 기록 저장</button><button disabled={!records.length} onClick={()=>download('anamorphic-observations.json',JSON.stringify({version:1,observations:records},null,2))}>기록 {records.length}개 내보내기 ↓</button></div><div className="record-list">{records.slice(0,5).map(r=><div className="record" key={r.id}><div><strong>{new Date(r.time).toLocaleString('ko-KR')}</strong><span>{observationLabel(r.success)} · 선명도 {r.clarity}/5 · {r.angle}° · {r.distance} mm · {observationLabel(r.perception)}</span></div><button onClick={()=>{setDraft(structuredClone(r.calibration));setDraftGrids(parseGrids(r.grids));setAutoDimensions(false);setDeviceChoice('manual');setMessage('관찰 기록의 보정값을 입력란에 불러왔습니다. 이미지를 다시 생성해 적용하세요.')}}>보정값 불러오기</button></div>)}</div><p className="fine">기록에는 마지막으로 생성한 보정값·격자 표시 여부·간격과 마지막 비교 모드가 저장됩니다. 예전 격자 없는 설정·기록은 격자를 끈 상태로 불러옵니다. 표시 영역이 0 × 0이면 이 이미지로 실험 모드를 열지 않았다는 뜻입니다. 브라우저 저장 공간은 삭제될 수 있으므로 기록을 내보내 사본을 보관하세요.</p></section>
 <footer><span>아나모픽 디스플레이 실험실 / 1단계</span><p>정적 투영만 실험합니다. 이 실험을 평가하기 전까지 센서, 카메라, 시점 추적, 애니메이션은 사용하지 않습니다.</p></footer></main></div>
 {message&&<div className="toast" role="status">{message}<button aria-label="알림 닫기" onClick={()=>setMessage('')}>×</button></div>}
 {experiment&&<div className="experiment" ref={stage} onClick={()=>{if(!controlsVisible)setControlsVisible(true)}}><img className="experiment-image" alt={mode==='projected'?'생성된 정적 아나모픽 표적':'변형하지 않은 원본 표적'} src={mode==='projected'?imageUrls.projected:imageUrls.original}/>{showRuler&&<div className="ruler" style={{width:`${20/active.display.widthMm*100}%`}}>20 mm</div>}{controlsVisible&&<div className="experiment-toolbar"><button onClick={()=>setMode(mode==='projected'?'original':'projected')}>{mode==='projected'?'보정 이미지':'원본'} · 전환</button><button aria-pressed={activeGrids.screen} onClick={()=>{setActiveGrids(g=>({...g,screen:!g.screen}));setDraftGrids(g=>({...g,screen:!activeGrids.screen}))}}>화면 격자 {activeGrids.screen?'켜짐':'꺼짐'}</button><button aria-pressed={activeGrids.plane} onClick={()=>{setActiveGrids(g=>({...g,plane:!g.plane}));setDraftGrids(g=>({...g,plane:!activeGrids.plane}))}}>평면 격자 {activeGrids.plane?'켜짐':'꺼짐'}</button><button onClick={()=>setShowRuler(!showRuler)}>20 mm 눈금자</button><button onClick={()=>{setControlsVisible(false);setShowRuler(false)}}>조작부 숨기기 · 화면을 누르면 다시 표시</button><button onClick={()=>void exit()}>나가기 ×</button>{autoDimensions&&<button onClick={applyViewportEstimate}>현재 표시 영역 크기 다시 적용</button>}<p>하늘색 점선: 화면 {activeGrids.screenSpacingMm} mm · 연두색 실선: 평면 {activeGrids.planeSpacingMm} mm</p><p>{fullscreenKind} · {Math.round(viewport.width)} × {Math.round(viewport.height)} CSS 픽셀 → {active.display.widthMm} × {active.display.heightMm} mm {viewportChanged?' · 표시 영역이 바뀌었습니다: 크기를 다시 적용하거나 다시 측정하세요':''}{zoomChanged?' · 화면 확대 감지: 확대를 100%로 되돌리세요':''}{viewport.width>0&&Math.abs(viewport.width/viewport.height-active.display.widthMm/active.display.heightMm)>.04?' · 가로세로 비율이 다릅니다: 현재 표시 영역을 측정하세요':''}</p></div>}</div>}
 </>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
